# Generated by Django 2.1.3 on 2018-11-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_auto_20181125_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='movies',
            field=models.ManyToManyField(to='example.Movie'),
        ),
    ]
